#!/bin/sh
# hack together apache and php entrytpoint/cmd

# from httpd-foreground
set -e

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid
httpd&
/usr/local/bin/docker-php-entrypoint php-fpm
